global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/*.tmpl'

route:
  group_by: ['...']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: alerta
  routes:
  - receiver: alerta
    matchers:
      - severity = 'critical'
    continue: true
  - receiver: telegram
    matchers:
      - severity =~ 'critical|warning'

receivers:
- name: 'alerta'
  webhook_configs:
  - url: 'http://10.101.0.67:8090/api/webhooks/prometheus?api-key=<api-key>'
    send_resolved: true

- name: 'telegram'
  telegram_configs:
  - bot_token: '<token>'
    api_url: 'https://api.telegram.org'
    chat_id: <chat_id>
    send_resolved: true
    message: '{{ template "telegram.message" . }}'
    parse_mode: HTML
