version: '3.7'

services:
  # WordPress
  wordpress:
    image: wordpress:php7.4-fpm
    container_name: p1_wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    networks:
      - monitoring

  # Nginx
  nginx:
    image: nginx:latest
    container_name: p1_nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - monitoring

  # Mysql
  db:
    image: mysql:5.7
    container_name: p1_mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    networks:
      - monitoring
    volumes:
      - ./data/vmstorage:/var/lib/mysql

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: p1_prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node_exporter
      - mysqld_exporter
      - blackbox_exporter
    networks:
      - monitoring

  # Alertmanager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: p3_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - monitoring

  # VictoriaMetrics
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: p2_victoria
    volumes:
      - ./data/vmstorage:/storage
    command:
      - '--storageDataPath=/storage'
      - '--retentionPeriod=2w'
    ports:
      - "8428:8428"
    networks:
      - monitoring

  # Node Exporter
  node_exporter:
    image: prom/node-exporter
    container_name: p1_node-exporter
    networks:
      - monitoring
    ports:
      - 9100:9100

  # MySQL Exporter
  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: p1_mysqld-exporter
    networks:
      - monitoring
    ports:
      - 9104:9104
    volumes:
      - ./exporters/mysqld.yml:/.my.cnf

  # Blackbox Exporter
  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: p1_blackbox-exporter
    volumes:
      - ./exporters/blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - "9115:9115"
    networks:
      - monitoring

networks:
  monitoring:
