global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 1m
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'mysql'
    scrape_interval: 1m
    static_configs:
      - targets:
          - 'db:3306'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysqld_exporter:9104

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://10.101.0.67
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
